[package]
name = "rust-raytracing"
version = "0.1.0"
edition = "2021"
default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rand = "0.8.5"
# lazy_static = "1.4.0"
# once_cell = "1.18.0"
image = "0.24.7"